server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_recycle_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Hyf20050528@
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.stu.entity

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.recycle.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

wechat:
  app-id: wx4f0e28dcebba0909
  app-secret: 94c634118718272a9bacf52f1921e298
  auth-url: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code
  test:
    mode: true
jwt:
  #my_jwt_secret1234567890
  secret: VGhpcyBpcyBhIHZlcnkgc2VjdXJlIGp3dCBzZWNyZXQgd2l0aCBtb3JlIHRoYW4gMzIgYnl0ZXMh
  expiration: 86400000
  header: Authorization

logging:
  level:
    com.recycle: debug
    org.springframework.web: info

#价格相关配置
recycling:
  price:
    pilot:
      period: true  # 是否试点期（前3个月）
      premium-rate: 0.20  # 试点期价格上浮比例
    base:
      waste_paper: 1.00    # 废纸/纸板基础价格(元/公斤)
      plastic_bottle: 2.00 # 塑料瓶基础价格
      old_clothes: 0.50     # 旧衣物基础价格
    pilot:
      waste_paper: 1.20    # 试点期废纸价格（上浮20%）
      plastic_bottle: 2.20 # 试点期塑料瓶价格（上浮20%）
      old_clothes: 0.60     # 试点期旧衣物价格（上浮20%